GET http://localhost:3001/api/users/

###
GET http://localhost:3001/api/users/62090c25f2ca3c6d53ba809b

###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "root",
    "name": "Admin",
    "password": "root"
}

###
POST http://localhost:3001/api/testing/reset
